NUM_FEATURES = 4

PRIMITIVE_SET_FUNCTIONS = ["add", "sub", "mul", "protdiv"]
TERMINAL_VARIABLES = [f"x{i}" for i in range(NUM_FEATURES)]
ERC_MIN = -0.5
ERC_MAX = 0.5
ERC_STEP = 0.1
ERC_VALUES = [round(ERC_MIN + i * ERC_STEP, 1)
              for i in range(int((ERC_MAX - ERC_MIN) / ERC_STEP) + 1)]

GP_POP_SIZE = 100
GP_GENERATIONS = 50
GP_TOURNAMENT_SIZE = 5
GP_INIT_DEPTH_MIN = 2
GP_INIT_DEPTH_MAX = 5
GP_MAX_TREE_DEPTH = 17
GP_CROSSOVER_PROB = 0.9
GP_MUTATION_PROB = 0.1
GP_MUTATION_DEPTH_MIN = 0
GP_MUTATION_DEPTH_MAX = 2
GP_INTERNAL_NODE_BIAS = 0.1
NUM_RUNS = 30

NUM_SYNTHETIC_PROBLEMS = 50
DATAGEN_GP_POP_SIZE = 2000
DATAGEN_GP_GENERATIONS = 100
NUM_SEMANTIC_SAMPLES = 100
KNN_K = 3
SD_MAX_THRESHOLD = 100.0
TARGET_NUM_PAIRS = 5_000_000

TRANSFORMER_NUM_HEADS = 8
TRANSFORMER_HIDDEN_DIM = 128
TRANSFORMER_NUM_ENCODER_LAYERS = 2
TRANSFORMER_NUM_DECODER_LAYERS = 2
TRANSFORMER_MAX_SEQ_LEN = 100
TRANSFORMER_DROPOUT = 0.1
TRANSFORMER_LEARNING_RATE = 1e-3
TRANSFORMER_EPOCHS = 8
TRANSFORMER_BATCH_SIZE = 256

TSGP_SD_DESIRED = 0.1
